CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USER_DATA(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    USERNAME VARCHAR(18) NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    FIRST_NAME VARCHAR(25),
    MIDDLE_NAME VARCHAR(25),
    LAST_NAME VARCHAR(25),
    EMAIL VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY_KEY_UD_ID PRIMARY KEY (ID)
);

INSERT INTO USER_DATA(USERNAME, PASSWORD, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL) VALUES ('Vrettost', '$2y$12$UzMgJOrluiuQ56l/5nysxOHgWkIbGSXd7ggqEhaYkxCDYh.iD/7Ee ', 'Haris', 'Marios', 'Vrettos', 'haris.vrettos@gmail.com');
INSERT INTO USER_DATA(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Ruby', '$2y$12$UzMgJOrluiuQ56l/5nysxOHgWkIbGSXd7ggqEhaYkxCDYh.iD/7Ee ', 'George', 'Roubie', 'george.roubie@gmail.com');