CREATE TABLE USER_DATA(
    ID UUID NOT NULL,
    USERNAME VARCHAR(40) NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    FIRST_NAME VARCHAR(40) NOT NULL,
    MIDDLE_NAME VARCHAR(40),
    LAST_NAME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CONSTRAINT PRIMARY_KEY_UD_ID PRIMARY KEY (ID)
);

INSERT INTO USER_DATA(ID, USERNAME, PASSWORD, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL) VALUES ('291e74c8-2c07-4024-a961-bef5f2f59a7b', 'Vrettost', '$2y$12$UzMgJOrluiuQ56l/5nysxOHgWkIbGSXd7ggqEhaYkxCDYh.iD/7Ee ', 'Haris', 'Marios', 'Vrettos', 'haris.vrettos@gmail.com');
INSERT INTO USER_DATA(ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL) VALUES ('4cf9c594-1729-4a6d-a45e-3cd97756b7cf', 'Ruby', '$2y$12$UzMgJOrluiuQ56l/5nysxOHgWkIbGSXd7ggqEhaYkxCDYh.iD/7Ee ', 'George', 'Roubie', 'george.roubie@gmail.com');