version: '3.8'
services:
  twix-user-service:
    build: ./../user-application
    ports:
      - 9300:9300
    depends_on:
      - twix-user-database
      - twix-user-migration
    container_name: twix-user-service

  twix-user-database:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - 5532:5432
    container_name: twix-user-database

  twix-user-migration:
    image: flyway/flyway:7
    environment:
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_SCHEMAS: twix_user
      FLYWAY_URL: jdbc:postgresql://twix-user-database:5432/userdb
    command: -connectRetries=60 migrate
    depends_on:
      - twix-user-database
    volumes:
      - ./migration-scripts:/flyway/sql
    container_name: twix-user-flyway

  twix-user-mocks:
    build: ./docker-mocks
    ports:
      - 9305:8080
    container_name: twix-user-wiremock
